# Generated by Django 6.0.3 on 2026-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=3)),
                ('retailer', models.CharField(max_length=50)),
                ('segment', models.CharField(choices=[('third_party', 'Third Party'), ('first_party', 'First Party')], default='first_party', max_length=50)),
            ],
        ),
    ]
