# Generated by Django 6.0.3 on 2026-03-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerecord',
            name='retailer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storerecord',
            name='segment',
            field=models.CharField(choices=[('third_party', 'Third Party'), ('first_party', 'First Party')], default='', max_length=50),
        ),
    ]
