# Generated by Django 6.0.3 on 2026-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotater', '0002_alter_storerecord_retailer_alter_storerecord_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerecord',
            name='segment',
            field=models.CharField(choices=[('Third Party', 'third_party'), ('First Party', 'first_party')], default='', max_length=50),
        ),
    ]
