# Generated by Django 6.0.3 on 2026-03-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotater', '0003_alter_storerecord_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerecord',
            name='segment',
            field=models.CharField(choices=[('Third Party', 'Third Party'), ('First Party', 'First Party')], default='', max_length=50),
        ),
    ]
